export * from "./audioPlayer/AudioPlayer.styles";
export * from "./audioPlayer/AudioPlayer";
export * from "./buttonsLogin/Button";
export * from "./buttonsLogin/button.styles";
export * from "./Cards/CardForPlaylist";
export { default as CardForPlaylistPlayerHome } from "./Cards/CardForPlaylistPlayerHome";
export * from "./Cards/CardForPlaylist";
export * from "./Cards/CardForPlaylistPlayer";
export * from "./Cards/CardForPlaylistPlayerHome";
export * from "./Cards/CardForTrack";
export { default as CardForPlaylistPlayer } from "./Cards/CardForPlaylistPlayer";

export { default as CardForTrack } from "./Cards/CardForTrack";

export * from "./footer/Footer";
// export * from "./footer/footer.styles";
export { default as InputForm } from "./inputsform/InputForm";
export * from "./inputsform/inputForm.styles";
export * from "./loader/Loader";
export * from "./log/Login";
export * from "./log/loginContainer.styles";
export * from "./logo/Logo";
export * from "./logo/logo.styles";
export * from "./mainHome/HomeMainContainer";
export * from "./mainHome/home-playlistContainer/PlaylistContainer.Styles";
export * from "./mainHome/home-playlistContainer/PlaylistContainerHome";
export * from "./mainHome/home-tracksContainer/TracksContainer";
export * from "./mainHome/home-tracksContainer/tracksContainer.Styles";
export * from "./mainHome/homeMainContainer.styles";
export * from "./mainPlayer/PlayerMainContainer";
export * from "./mainPlayer/player-playerContainer/PlayerContainer";
export * from "./mainPlayer/player-playerContainer/playerContainer.styles";
export * from "./mainPlayer/playerMainContainer.styles";
export * from "./mainPlaylist/PlaylistMainContainer";
export * from "./mainPlaylist/playlistMainContainer.styles";
export * from "./mainProfile/ProfileMainContainer";
export * from "./mainProfile/profileMainContainer.styles";
export * from "./player/Player";

export * from "./register/RegisterSection";
export * from "./register/registerSection.styles";
export * from "./router/PrivateRoute";
export * from "./router/PublicRoute";
export * from "./searchBar/SearchBar";
export * from "./searchBar/searchBar.Styles";
export * from "./sideBar/SideBar";
export * from "./sideBar/favoritesSection/FavoritesSectionContainer";
export * from "./sideBar/favoritesSection/favoritesSectionContainer.styles";
export * from "./sideBar/homeSection/HomeSectionContainer";
export * from "./sideBar/homeSection/homeSectionContainer.styles";
export * from "./sideBar/playlistSection/PlaylistSectionContainer";
export * from "./sideBar/playlistSection/playlistSectionContainer.styles";
export * from "./sideBar/sidebar.styles";
